# Generated by Django 2.2.1 on 2019-05-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0003_auto_20190522_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='url',
            new_name='path',
        ),
    ]
