# Generated by Django 2.2.1 on 2019-05-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0004_auto_20190522_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='000', max_length=10),
            preserve_default=False,
        ),
    ]
