# Generated by Django 2.2.1 on 2019-05-22 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0006_auto_20190522_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='rid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
