version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  
  redis: 
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:    
      - "./redisdata:/data"
