# Generated by Django 2.2.1 on 2019-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0002_auto_20190520_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mask',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='official_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='subtype',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
