# Generated by Django 2.2.1 on 2019-05-20 14:32

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Item', '0003_auto_20190520_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_owner', models.CharField(max_length=80)),
                ('amount', models.IntegerField(max_length=80)),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=None)),
                ('category_id', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('iso_currency_code', models.CharField(max_length=5)),
                ('location', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=80)),
                ('payment_meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('pending', models.BooleanField()),
                ('pending_transaction_id', models.CharField(max_length=80)),
                ('transaction_id', models.CharField(max_length=80)),
                ('transaction_type', models.CharField(max_length=80)),
                ('unofficial_currency_code', models.CharField(max_length=80)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
