# Generated by Django 2.2.1 on 2019-05-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0005_auto_20190520_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_owner',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
