# Generated by Django 2.2.1 on 2019-05-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0009_auto_20190521_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='a',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
