# Generated by Django 2.2.1 on 2019-05-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0010_auto_20190522_0527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HookCalls',
        ),
    ]
